runtime: nodejs16
env: standard
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
env_variables:
  API_KEY: '0000'
  spreadSheetID: '1t-sCJ_CmXedbU8M7BlZhdMHHIFOgKO6Mgm998EXuz20'
  DEV: 'false'
  EMAIL: 'HoraireDelta2@gmail.com'
  EMAIL_PASSWORD: 'yhcphwckljjkcpqg'
  NODE_TLS_REJECT_UNAUTHORIZED: 0
  PORT: 8080
